name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13.1

      - name: Install Python Virtual Environment
        run: pip3 install virtualenv

      - name: Create Virtual Environment
        uses: actions/cache@v4
        id: cache-env
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      
      - name: Activate Virtual Environment
        run: python3 -m venv venv && source venv/bin/activate && python3 -m pip install -r requirements.txt
        
      - name: Run Tests
        run: .venv/bin/activate && pytest

      - name: Create archive of dependencies
        run: cd .venv/lib/python3.13/site-packages && zip -r9 ../../../../api.zip .

      - name: Add API files to ZIP files
        run: cd ./api && zip -g ../api.zip -r .

      - name: Upload ZIP file artufact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: api.zip
